### ISSUE TITLE
Connecting to mongolab

### ISSUE THREAD

**Issue by pwheden** [linmdotor/DataMining_LinkedIn#1]
Hi Lin! I am not sure if you remember this project anymore haha, but I was trying to looking at it again, and connecting to MongoLab. Can you tell me how you did it? I tried to change in the mongoid.yml file but then I get an error for the ruby-code, which I think you didn't get ... I probably am connecting wrong:

I comment out everything and add this in mongoid.yml:

```
#development:
#   sessions:
#     default:

#       uri: 'mongodb://pwheden:2.5liter/dagLAB@ds039211.mongolab.com:39211/linkedin_project'

#       options:

#         max_retries: 30
#         retry_interval: 1
#         timeout: 15
#         refresh_interval: 10
# test:
#   sessions:
#     default:

#       uri: 'mongodb://pwheden:2.5liter/dagLAB@ds039211.mongolab.com:39211/linkedin_project'

#       options:

#         max_retries: 30
#         retry_interval: 1
#         timeout: 15
#         refresh_interval: 10
# production:
#   sessions:
#     default:

#       uri: 'mongodb://pwheden:2.5liter/dagLAB@ds039211.mongolab.com:39211/linkedin_project'

#       options:

#         max_retries: 30
#         retry_interval: 1
#         timeout: 15
#         refresh_interval: 10
```

If you don't remember it's fine, I just wanted to see if I could get it running on Heroku and then I need mongolab..

**Comment by linmdotor** [comment]
Hi William!
The last version with the MongoLab connection I have is like this:
(All this code must be in the "development" section)

``` ruby
development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:       
      uri: 'mongodb://lin:123@ds039211.mongolab.com:39211/linkedin_project'

  options:
    raise_not_found_error: false #this is no return nil in the query Company.find_by name: company (strictly 4 spaces before not 6)
```

(Being "lin" and "123" the user and pass in MongoLab.

I tried to run it, and I obtained an error too:

```
No route matches {:action=>"accept_crawl", :company=>"ebay", :controller=>"indices", :country=>"es", :id=>""} missing required keys: [:id]
```

It appears to have the field "id" empty when it connects to MongoLab, because in local it works fine.

I'll take a look at it.

**Comment by linmdotor** [comment]
the error could be in "indices_controller.rb"; this line returns a empty string:

```
id = User.where(:url => url.downcase).pluck(:_id)[0].to_s
```

**Comment by linmdotor** [comment]
ehhhhh... nope.
The problem should be in your MongoLab database, because in my MongoLab account I have a database with this connection, that works fine.

```
uri: 'mongodb://lin:123@ds039058.mongolab.com:39058/datamining_linkedin_db'
```

Maybe our DB users have read-only permissions in your DB?
Maybe make public the connection credentials in github is not a good idea, and someone has corrupted the DB? hehe
Or you can try to create a new database in MongoLab. ¿?

PD: I've updated the project with my connection. Try it again; It should work like that.

**Comment by pwheden** [comment]
Thanks for you help Lin. I had to configure production to also connect to mongolab because apparently this is what the app uses with Heroku. I can run the app online now, and it works if the data is already in the database, however, if I want to search for new data I get redirected to the sad smiley ( ":(") error we had that said something was wrong. 

After having googled I found that processes that take longer than 30 seconds gets killed by Heroku, and so the crawler doesn't work. I will look into this, because locally the project works perfect even when all data is run through mongolab.

I will continue to work a bit on this project because I think it's fun - and don't feel the need to spend a lot of time if you don't want. I am sorry if you get notifications from me hahah! If you want I can Fork the project and keep updating just for myself??

Have a wonderful summer!
